# Generated by Django 5.2.6 on 2025-09-27 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('donor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('location_lat', models.FloatField()),
                ('location_long', models.FloatField()),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('receiver_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('location_lat', models.FloatField()),
                ('location_long', models.FloatField()),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodDonation',
            fields=[
                ('donation_id', models.AutoField(primary_key=True, serialize=False)),
                ('food_type', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(default='kg', max_length=20)),
                ('expiry_time', models.DateTimeField()),
                ('status', models.CharField(default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.donor')),
            ],
        ),
        migrations.CreateModel(
            name='MLPredictions',
            fields=[
                ('prediction_id', models.AutoField(primary_key=True, serialize=False)),
                ('expiry_risk', models.FloatField(default=0.0)),
                ('suggested_pickup_time', models.DateTimeField(blank=True, null=True)),
                ('model_version', models.CharField(default='v1.0', max_length=20)),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('predicted_for', models.CharField(blank=True, max_length=50, null=True)),
                ('donation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fooddonation')),
            ],
        ),
        migrations.CreateModel(
            name='DonorAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('donor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.donor')),
            ],
            options={
                'unique_together': {('donor_id', 'address')},
            },
        ),
        migrations.CreateModel(
            name='PickupSchedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('priority_score', models.FloatField(default=0.0)),
                ('scheduled_time', models.DateTimeField()),
                ('pickup_status', models.CharField(default='pending', max_length=20)),
                ('donation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fooddonation')),
                ('receiver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.receiver')),
            ],
            options={
                'unique_together': {('donation_id', 'receiver_id')},
            },
        ),
        migrations.CreateModel(
            name='ReceiverAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('receiver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.receiver')),
            ],
            options={
                'unique_together': {('receiver_id', 'address')},
            },
        ),
    ]
