# Generated by Django 5.2.6 on 2025-09-29 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_donor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddonation',
            name='assigned_receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.receiver'),
        ),
    ]
