# Generated by Django 5.2.6 on 2025-09-29 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_fooddonation_assigned_receiver'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pickupschedule',
            unique_together=set(),
        ),
    ]
