# Generated by Django 5.2.6 on 2025-09-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_pickupschedule_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddonation',
            name='priority_score',
            field=models.FloatField(default=0.0),
        ),
    ]
